default_platform(:ios)

platform :ios do
 desc "Push a new release build to the App Store"
 lane :release do
   match(type: "appstore")
   increment_build_number(xcodeproj: "mobileBetApp.xcodeproj")
   build_app(workspace: "BetMobileApp.xcworkspace", scheme: "mobileBetApp-PROD")
   upload_to_app_store(
     skip_waiting_for_build_processing: true,
     submit_for_review: true,
     force: true,
   )
   clean_build_artifacts
 end

 desc "Push a new release build to TestFlight"
 lane :beta do
   match(type: "appstore")
   increment_build_number(xcodeproj: "mobileBetApp.xcodeproj")
   build_app(workspace: "BetMobileApp.xcworkspace", scheme: "mobileBetApp-PROD")
   upload_to_testflight(
     skip_waiting_for_build_processing: true
   )
   clean_build_artifacts
    end

   end

